### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [llmarlow/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by llmarlow** [comment]
I have added <meta name="viewport" content="width=device-width, initial-scale=1"> to the head of my application.html.erb. Was this what you meant?

**Comment by kenmazaika** [comment]
Awesome.  Thumbs up.  You have it perfectly. :+1:
